[project]
name = "fastapi-example"
version = "0.0.0"
description = "My awesome Python library"
classifiers = ["Private :: Do Not Upload"]
requires-python = ">=3.12"
dependencies = [
    "dinkleberg[fastapi]>=0.3.0",
    "uvicorn>=0.40.0",
]
